package org.apache.jsp.TableTools_002d2_1_4;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class object_005fdata_005fselect_005fall_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/ico\" href=\"http://www.datatables.net/media/images/favicon.ico\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<title>DataTables example</title>\n");
      out.write("\t\t<style type=\"text/css\" title=\"currentStyle\">\n");
      out.write("\t\t\t@import \"../media/css/demo_page.css\";\n");
      out.write("\t\t\t@import \"../media/css/demo_table.css\";\n");
      out.write("\t\t\t@import \"media/css/TableTools.css\";   /* Necessario per TableTools */\n");
      out.write("\t\t</style>\n");
      out.write("\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../media/js/jquery.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../media/js/jquery.dataTables.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"./media/js/ZeroClipboard.js\"></script> <!-- /* Necessario per TableTools */ --> \n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"./media/js/TableTools.js\"></script> <!-- /* Necessario per TableTools */ -->\n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\">\n");
      out.write("\t\t\n");
      out.write("\t\tvar oTable;\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function() {\n");
      out.write("\t\toTable = $('#example').dataTable( {\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t/* Inserisce i pulsanti di selezione righe */ \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t// \"sDom\": \"<'row-fluid'<'span6'f><'span6'T>r><<'span6'l>>t<'row-fluid'<'span6'i><'span6'p>>\",\n");
      out.write("\t\t\t\t\"sDom\": 'T<\"clear\">lfrtip',\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\"oTableTools\": {\n");
      out.write("\t\t\t\t\t\"sRowSelect\": \"multi\",\n");
      out.write("\t\t\t\t\t\"aButtons\": [\n");
      out.write("\t\t\t\t\t\t{\n");
      out.write("\t\t                    \"sExtends\":     \"select_all\",\n");
      out.write("\t\t                    \"sButtonText\": \"Seleziona tutto\"\n");
      out.write("\t\t                } , \n");
      out.write("\t\t                {\n");
      out.write("\t\t                    \"sExtends\":     \"select_none\",\n");
      out.write("\t\t                    \"sButtonText\": \"Annulla selezione\"\n");
      out.write("\t\t                }\n");
      out.write("\t\t\t\t\t] \n");
      out.write("\t\t\t\t} ,\n");
      out.write("\t\t\t\t/* ---------------------------------------- */\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t//\"sDom\": '<\"custom_toolbar\"><\"clear\">lfrtip',\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\"bProcessing\": true,\n");
      out.write("\t\t\t\t\"bServerSide\": true,\n");
      out.write("\t\t\t\t\"sAjaxSource\": \"../jsp/dati.jsp\",\n");
      out.write("\t\t\t\t\"sServerMethod\": \"POST\" ,\n");
      out.write("\t\t\t\t\"aaSorting\": [ [1,'asc'] ], // Ordinamento secondo la colonna <n> verso <asc/desc>. Si puo' aggiungere un \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// ulteriore criterio di ordinamento aggiungendo un altro array simile al primo \n");
      out.write("\t\t\t\t\"aoColumns\": [\n");
      out.write("\t\t\t\t// colonna 1 nella tabella { mData: <nome_colonna_nel_DB> , ... } \n");
      out.write("\t\t\t\t// colonna 2 nella tabella { mData: <nome_colonna_nel_DB> , \"bSortable\": false , ... } // ordinamento disabilitato \n");
      out.write("\t\t\t\t// colonna .. nella tabella { mData: <nome_colonna_nel_DB> , ... } \n");
      out.write("\t\t\t\t \t{ \"sClass\": \"center\", \"bSortable\": false ,\"mData\": \"img\", \"bSearchable\": false },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"engine\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"browser\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"platform\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"version\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"grade\" }\n");
      out.write("\t\t\t\t] ,\n");
      out.write("\t\t\t\t\"oLanguage\": {\n");
      out.write("\t\t\t\t    \"sEmptyTable\":     \"Nessun dato presente nella tabella\",\n");
      out.write("\t\t\t\t    \"select_all\":\t\t\"Seleziona tutti\",\n");
      out.write("\t\t\t\t    \"sInfo\":           \"Vista da _START_ a _END_ di _TOTAL_ elementi\",\n");
      out.write("\t\t\t\t    \"sInfoEmpty\":      \"Vista da 0 a 0 di 0 elementi\",\n");
      out.write("\t\t\t\t    \"sInfoFiltered\":   \"(filtrati da _MAX_ elementi totali)\",\n");
      out.write("\t\t\t\t    \"sInfoPostFix\":    \"\",\n");
      out.write("\t\t\t\t    \"sInfoThousands\":  \",\",\n");
      out.write("\t\t\t\t    \"sLengthMenu\":     \"Visualizza _MENU_ elementi\",\n");
      out.write("\t\t\t\t    \"sLoadingRecords\": \"Caricamento...\",\n");
      out.write("\t\t\t\t    \"sProcessing\":     \"Elaborazione...\",\n");
      out.write("\t\t\t\t    \"sSearch\":         \"Cerca:\",\n");
      out.write("\t\t\t\t    \"sZeroRecords\":    \"La ricerca non ha portato alcun risultato.\",\n");
      out.write("\t\t\t\t    \"oPaginate\": {\n");
      out.write("\t\t\t\t        \"sFirst\":      \"Inizio\",\n");
      out.write("\t\t\t\t        \"sPrevious\":   \"Precedente\",\n");
      out.write("\t\t\t\t        \"sNext\":       \"Successivo\",\n");
      out.write("\t\t\t\t        \"sLast\":       \"Fine\"\n");
      out.write("\t\t\t\t    },\n");
      out.write("\t\t\t\t    \"oAria\": {\n");
      out.write("\t\t\t\t        \"sSortAscending\":  \": attiva per ordinare la colonna in ordine crescente\",\n");
      out.write("\t\t\t\t        \"sSortDescending\": \": attiva per ordinare la colonna in ordine decrescente\"\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t} ,\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t// Dati custom da inviare al jsp nella chiamata ajax come parametri aggiuntivi della request \n");
      out.write("\t\t\t\t\"fnServerParams\": function ( aoData ) {\n");
      out.write("\t\t            aoData.push({ \"name\": \"detailsImgURL\" ,\t\t\t\"value\": \"../examples/examples_support/details_open.png\" } ,\n");
      out.write("\t\t            \t\t\t{ \"name\": \"segnapostoPerNulli\" ,\t\"value\": \"-\"  } ,\n");
      out.write("// \t\t            \t\t\t{ \"name\": \"stampaQuery\" ,\t\t\t\"value\": \"true\" } ,\n");
      out.write("\t\t            \t\t\t{ \"name\": \"debugRequestParams\" ,\t\"value\": \"true\" } ,\n");
      out.write("\t\t            \t\t\t{ \"name\": \"pathReqParamsDebugLog\" ,\t\"value\": \"c:/logTestDB.txt\" }\n");
      out.write("\t\t            );\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} );\n");
      out.write("\t\t\n");
      out.write("\t\t// Elenco pulsanti da aggiungere alla toolbar personalizzata \n");
      out.write("\t\tvar bSeleziona_tutto = \"<input id='bSeleziona_tutto' type='button' value='Seleziona tutto' />\";\t\n");
      out.write("\t\tvar bAnnulla_selezione = \"<input id='bAnnulla_selezione' type='button' value='Annulla seleziona' />\";\t\n");
      out.write("\t\tvar bAzione = \"<input id='bAzione' type='button' value='Azione' />\";\t\n");
      out.write("\t\t\n");
      out.write("\t\t// Aggiunge i pulsanti al div custom_toolbar \n");
      out.write("\t\t$(\"div.custom_toolbar\").html(\tbSeleziona_tutto + \" \" \t\n");
      out.write("\t\t\t\t\t\t\t\t\t+ bAnnulla_selezione + \" \" \n");
      out.write("\t\t\t\t\t\t\t\t\t+ bAzione); \n");
      out.write("\t\t\n");
      out.write("\t\t$(\"div.custom_toolbar #bSeleziona_tutto\").on('click', function (e) {\n");
      out.write("\t\t\t$(oTable).find('tr').each( function(i,e) {\n");
      out.write("\t\t\t\tvar $tr = $(e);\n");
      out.write("\t\t\t\tif ( ! $tr.hasClass('row_selected') )\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\t$tr.trigger('click');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} );\n");
      out.write("\t\t} );\n");
      out.write("\n");
      out.write("\t\t$(\"div.custom_toolbar #bAnnulla_selezione\").on('click', function (e) {\n");
      out.write("\t\t\t$(oTable).find('tr').each( function(i,e) {\n");
      out.write("\t\t\t\tvar $tr = $(e);\n");
      out.write("\t\t\t\tif ( $tr.hasClass('row_selected') )\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\t$tr.trigger('click');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} );\n");
      out.write("\t\t} );\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"div.custom_toolbar #bAzione\").on('click', function (e) {\n");
      out.write("\t\t\tvar dati = \"\";\n");
      out.write("\t\t\tfnGetSelected( oTable ).each( function() {\n");
      out.write("\t\t\t\tvar riga = \"\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif (dati.length > 0)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tdati += \"\\n\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t$(this).find('td').each(function () {\n");
      out.write("\t\t\t\t\tif (riga.length > 0)\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\triga += \" - \";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\triga += $(this).text();\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tdati += riga;\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\talert(dati);\n");
      out.write("\t\t} );\n");
      out.write("\t\t\n");
      out.write("\t\tfunction fnGetSelected( oTableLocal )\n");
      out.write("\t\t{\n");
      out.write("\t\t    return oTableLocal.$('tr.row_selected');\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Click event handler astericoQui-> /\n");
      out.write("\t    $('#example tbody tr').live('click', function () {\n");
      out.write("\t        $(this).toggleClass('row_selected');\n");
      out.write("\t    } );\n");
      out.write("\t\t/* -- */\n");
      out.write("\t\t\n");
      out.write("\t\t// disabilita la ricerca istantanea e impone \"invio\" per confermare la ricerca \n");
      out.write("\t\t$('.dataTables_filter input')\n");
      out.write("\t    \t.unbind('keypress keyup')\n");
      out.write("\t    \t.bind('keypress keyup', function(e){\n");
      out.write("\t\t      \tif ( e.keyCode == 13 )\n");
      out.write("\t\t      \t{\n");
      out.write("\t\t      \t\toTable.fnFilter( $(this).val(), null );\n");
      out.write("\t\t      \t}\n");
      out.write("\t      \t\n");
      out.write("    \t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t} );\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\tfunction fnFormatDetails ( nTr )\n");
      out.write("\t\t{\n");
      out.write("\t\t    var aData = oTable.fnGetData( nTr );\n");
      out.write("\t\t    var sOut =\t'<table cellpadding=\"5\" cellspacing=\"0\" border=\"0\" style=\"padding-left:50px;\">';\n");
      out.write("\t\t    sOut += \t'\t<tr> ';\n");
      out.write("\t\t    sOut += \t'\t\t<td>Rendering engine:</td>';\n");
      out.write("\t\t    sOut += \t'\t\t<td>'+ aData['browser'] +' '+ aData['engine'] +'</td>';\n");
      out.write("\t\t    sOut +=\t\t'\t</tr>';\n");
      out.write("\t\t    sOut += \t'\t<tr> ';\n");
      out.write("\t\t    sOut += \t'\t\t<td>Link to source:</td>';\n");
      out.write("\t\t    sOut += \t'\t\t<td>Could provide a link here</td>';\n");
      out.write("\t\t    sOut +=\t\t'\t</tr>';\n");
      out.write("\t\t    sOut += \t'\t<tr> ';\n");
      out.write("\t\t    sOut += \t'\t\t<td>Extra info:</td>';\n");
      out.write("\t\t    sOut += \t'\t\t<td>And any further details here (images etc)</td>';\n");
      out.write("\t\t    sOut +=\t\t'\t</tr>';\n");
      out.write("\t\t    sOut +=\t\t'</table>';\n");
      out.write("\t\t     \n");
      out.write("\t\t    return sOut;\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t    $('#example tbody td img').live( 'click', function () {\n");
      out.write("\t        var nTr = $(this).parents('tr')[0];\n");
      out.write("\t        if ( oTable.fnIsOpen(nTr) )\n");
      out.write("\t        {\n");
      out.write("\t            /* Comprime la riga gia' aperta */\n");
      out.write("\t            this.src = \"../examples/examples_support/details_open.png\";\n");
      out.write("\t            oTable.fnClose( nTr );\n");
      out.write("\t        }\n");
      out.write("\t        else\n");
      out.write("\t        {\n");
      out.write("\t            /* Espande la riga */\n");
      out.write("\t            this.src = \"../examples/examples_support/details_close.png\";\n");
      out.write("\t            oTable.fnOpen( nTr, fnFormatDetails(nTr), 'details' );\n");
      out.write("\t        }\n");
      out.write("\t    } );\n");
      out.write("\t    \n");
      out.write("\t\t</script>\n");
      out.write("\t</head>\n");
      out.write("\t<body id=\"dt_example\">\n");
      out.write("\t\t<div id=\"container\">\n");
      out.write("\t\t\t<div class=\"full_width big\">\n");
      out.write("\t\t\t\tDataTables server-side processing example - object based data source\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<h1>Live example</h1>\n");
      out.write("\t\t\t<div id=\"dynamic\">\n");
      out.write("\t\t\t\n");
      out.write("<!-- \t\t\tStruttura statica della tabella ++++ -->\n");
      out.write("\n");
      out.write("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display\" id=\"example\">\n");
      out.write("\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th width=\"4%\"></th>\t\t\t<!-- Colonna per il pulsantino che espande/comprime la riga -->\n");
      out.write("\t\t\t\t\t\t<th width=\"25%\">Rendering engine</th>\n");
      out.write("\t\t\t\t\t\t<th width=\"20%\">Browser</th>\n");
      out.write("\t\t\t\t\t\t<th width=\"25%\">Platform(s)</th>\n");
      out.write("\t\t\t\t\t\t<th width=\"16%\">Engine version</th>\n");
      out.write("\t\t\t\t\t\t<th width=\"10%\">CSS grade</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\" class=\"dataTables_empty\">Loading data from server</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t<tfoot>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th></th>\t\t\t\t\t\t<!-- Colonna per il pulsantino che espande/comprime la riga -->\n");
      out.write("\t\t\t\t\t\t<th>Rendering engine</th>\n");
      out.write("\t\t\t\t\t\t<th>Browser</th>\n");
      out.write("\t\t\t\t\t\t<th>Platform(s)</th>\n");
      out.write("\t\t\t\t\t\t<th>Engine version</th>\n");
      out.write("\t\t\t\t\t\t<th>CSS grade</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tfoot>\n");
      out.write("\t\t\t</table>\n");
      out.write("<!-- \t\t\tStruttura statica della tabella **** -->\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"spacer\"></div>\n");
      out.write("\t\t\t\n");
      out.write("<!-- \t\t\tCodice per la manipolazione dinamca tabella ++++ -->\t\t\t\n");
      out.write("\t\t\t<h1>Codice dietro l'esempio</h1>\n");
      out.write("\t\t\t<pre class=\"brush: js;\">$('#example').dataTable( {\n");
      out.write("\t\t\t\t\"bProcessing\": true,\n");
      out.write("\t\t\t\t\"bServerSide\": true,\n");
      out.write("\t\t\t\t\"sAjaxSource\": \"../jsp/dati.jsp\",\n");
      out.write("\t\t\t\t\"sServerMethod\": \"POST\" ,\n");
      out.write("\t\t\t\t\"aaSorting\": [ [1,'asc'] ], // ordinamento secondo la colonna &lt;n&gt; verso &lt;asc/desc&gt; \n");
      out.write("\t\t\t\t\"aoColumns\": [\n");
      out.write("\t\t\t\t// colonna 1 nella tabella { mData: &lt;nome_colonna_nel_DB&gt; , ... } \n");
      out.write("\t\t\t\t// colonna 2 nella tabella { mData: &lt;nome_colonna_nel_DB&gt; , \"bSortable\": false , ... } // ordinamento disabilitato \n");
      out.write("\t\t\t\t// colonna .. nella tabella { mData: &lt;nome_colonna_nel_DB&gt; , ... } \n");
      out.write("\t\t\t\t \t{ \"sClass\": \"center\", \"bSortable\": false ,\"mData\": \"img\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"engine\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"browser\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"platform\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"version\" },\n");
      out.write("\t\t\t\t\t{ \"mData\": \"grade\" }\n");
      out.write("\t\t\t\t] ,\n");
      out.write("\t\t\t\t\"oLanguage\": {\n");
      out.write("\t\t\t\t    \"sEmptyTable\":     \"Nessun dato presente nella tabella\",\n");
      out.write("\t\t\t\t    \"sInfo\":           \"Vista da _START_ a _END_ di _TOTAL_ elementi\",\n");
      out.write("\t\t\t\t    \"sInfoEmpty\":      \"Vista da 0 a 0 di 0 elementi\",\n");
      out.write("\t\t\t\t    \"sInfoFiltered\":   \"(filtrati da _MAX_ elementi totali)\",\n");
      out.write("\t\t\t\t    \"sInfoPostFix\":    \"\",\n");
      out.write("\t\t\t\t    \"sInfoThousands\":  \",\",\n");
      out.write("\t\t\t\t    \"sLengthMenu\":     \"Visualizza _MENU_ elementi\",\n");
      out.write("\t\t\t\t    \"sLoadingRecords\": \"Caricamento...\",\n");
      out.write("\t\t\t\t    \"sProcessing\":     \"Elaborazione...\",\n");
      out.write("\t\t\t\t    \"sSearch\":         \"Cerca:\",\n");
      out.write("\t\t\t\t    \"sZeroRecords\":    \"La ricerca non ha portato alcun risultato.\",\n");
      out.write("\t\t\t\t    \"oPaginate\": {\n");
      out.write("\t\t\t\t        \"sFirst\":      \"Inizio\",\n");
      out.write("\t\t\t\t        \"sPrevious\":   \"Precedente\",\n");
      out.write("\t\t\t\t        \"sNext\":       \"Successivo\",\n");
      out.write("\t\t\t\t        \"sLast\":       \"Fine\"\n");
      out.write("\t\t\t\t    },\n");
      out.write("\t\t\t\t    \"oAria\": {\n");
      out.write("\t\t\t\t        \"sSortAscending\":  \": attiva per ordinare la colonna in ordine crescente\",\n");
      out.write("\t\t\t\t        \"sSortDescending\": \": attiva per ordinare la colonna in ordine decrescente\"\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} );\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t// disabilita la ricerca istantanea e impone \"invio\" per confermare la ricerca \n");
      out.write("\t\t$('.dataTables_filter input')\n");
      out.write("\t    \t.unbind('keypress keyup')\n");
      out.write("\t    \t.bind('keypress keyup', function(e){\n");
      out.write("\t\t      \tif ( e.keyCode == 13 )\n");
      out.write("\t\t      \t{\n");
      out.write("\t\t      \t\toTable.fnFilter( $(this).val(), null );\n");
      out.write("\t\t      \t}\n");
      out.write("\t      \t\n");
      out.write("    \t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t} );\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\tfunction fnFormatDetails ( nTr )\n");
      out.write("\t\t{\n");
      out.write("\t\t    var aData = oTable.fnGetData( nTr );\n");
      out.write("\t\t    var sOut =\t'&lt;table cellpadding=\"5\" cellspacing=\"0\" border=\"0\" style=\"padding-left:50px;\"&gt;';\n");
      out.write("\t\t    sOut += \t'\t&lt;tr&gt; ';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;Rendering engine:&lt;/td&gt;';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;'+ aData['browser'] +' '+ aData['engine'] +'&lt;/td&gt;';\n");
      out.write("\t\t    sOut +=\t\t'\t&lt;/tr&gt;';\n");
      out.write("\t\t    sOut += \t'\t&lt;tr&gt; ';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;Link to source:&lt;/td&gt;';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;Could provide a link here&lt;/td&gt;';\n");
      out.write("\t\t    sOut +=\t\t'\t&lt;/tr&gt;';\n");
      out.write("\t\t    sOut += \t'\t&lt;tr&gt; ';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;Extra info:&lt;/td&gt;';\n");
      out.write("\t\t    sOut += \t'\t\t&lt;td&gt;And any further details here (images etc)&lt;/td&gt;';\n");
      out.write("\t\t    sOut +=\t\t'\t&lt;/tr&gt;';\n");
      out.write("\t\t    sOut +=\t\t'&lt;/table&gt;';\n");
      out.write("\t\t     \n");
      out.write("\t\t    return sOut;\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t    $('#example tbody td img').live( 'click', function () {\n");
      out.write("\t        var nTr = $(this).parents('tr')[0];\n");
      out.write("\t        if ( oTable.fnIsOpen(nTr) )\n");
      out.write("\t        {\n");
      out.write("\t            /* Comprime la riga gia' aperta */\n");
      out.write("\t            this.src = \"../examples_support/details_open.png\";\n");
      out.write("\t            oTable.fnClose( nTr );\n");
      out.write("\t        }\n");
      out.write("\t        else\n");
      out.write("\t        {\n");
      out.write("\t            /* Espande la riga */\n");
      out.write("\t            this.src = \"../examples_support/details_close.png\";\n");
      out.write("\t            oTable.fnOpen( nTr, fnFormatDetails(nTr), 'details' );\n");
      out.write("\t        }\n");
      out.write("\t    } );\n");
      out.write("} );</pre>\n");
      out.write("<!-- \t\t\tCodice per la manipolazione dinamca tabella **** -->\n");
      out.write("\t\t\t<style type=\"text/css\">\n");
      out.write("\t\t\t\t@import \"../examples_support/syntax/css/shCore.css\";\n");
      out.write("\t\t\t</style>\n");
      out.write("\t\t\t<script type=\"text/javascript\" language=\"javascript\" src=\"../examples_support/syntax/js/shCore.js\"></script>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
